### PR TITLE
Refactored code to functions instead of BaseHandler methods & set up Travis CI.

### PR DESCRIPTION
**Pull request by agjwong**

### CODE REVIEW

**Comment by mreid-moz** [comment]
Looks good to me! Please increment the version in `setup.py` to `0.3.0`

**Comment by mreid-moz** [comment]
@agjwong Can you fix the conflicts with master and update the package version?

**Comment by agjwong** [comment]
@mreid-moz merged in fixes and updated version

**Comment by mreid-moz** [comment]
Looks good, thanks!

**Pull request merged**
